### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [ACOTRINA/ISII-WORKSHOPS-BOTS_PARA_SMS_WS#1]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by ACOTRINA** [comment]
Thank you, we will make the changes as soon as possible.

**Comment by jose598** [comment]
Thank you @ACOTRINA.

**Comment by ACOTRINA** [comment]
The issue has been categorized and we added the milestone.

**Comment by ACOTRINA** [comment]
We will proceed to process  the request, @esyugcha will be the assigned analyst, @oyguzman14  will develop the solution, and 
@ACOTRINA  will perform the tests

**Comment by jose598** [comment]
Thank you

**Comment by ACOTRINA** [comment]
I attach the Analysis Report, the time for the changes in the requirements has been estimated to less than 8 hours
@jose598 do you agree with this?
[Impact analysis.docx](https://github.com/ACOTRINA/ISII-WORKSHOPS-BOTS_PARA_SMS_WS/files/7909871/Impact.analysis.docx)

**Comment by jose598** [comment]
Hi @ACOTRINA not at all.
The first rule mentioned is about discount for couple, it means discount $50 for each one.

**Comment by jose598** [comment]
When you change this, please send me the document again and start working on the issue. @ACOTRINA

**Comment by ACOTRINA** [comment]
Hi @jose598 I attached the new document, where I specify that for the first condition you need to decrease $100
[Impact analysis.docx](https://github.com/ACOTRINA/ISII-WORKSHOPS-BOTS_PARA_SMS_WS/files/7917355/Impact.analysis.docx)

**Comment by jose598** [comment]
It's good, continue with the next step @ACOTRINA

**Comment by ACOTRINA** [comment]
The solution has been built and the code has been modified
https://github.com/ACOTRINA/ISII-WORKSHOPS-BOTS_PARA_SMS_WS/blob/25b7f6ae259252f85248309577ffa74838d6277b/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L100-L125

**Comment by jose598** [comment]
Thank you @ACOTRINA. 
It looks good, please make the test plan for closing this issue.

**Comment by ACOTRINA** [comment]
The previous steps have already been executed, analysis and programming

**Comment by jose598** [comment]
@ACOTRINA Got it.

**Comment by oyguzman14** [comment]
Hi @jose598 I attach the enactment of the solution
[Enactment of the solution.docx](https://github.com/ACOTRINA/ISII-WORKSHOPS-BOTS_PARA_SMS_WS/files/7917585/Enactment.of.the.solution.docx)

**Comment by ACOTRINA** [comment]
Hi @jose598 Please let me know if you are able to understand all the steps and if you are happy with the results
